### ISSUE TITLE
Inquiry about Hardware Setup for Evaluating Performance with More than 3 Layers

### ISSUE THREAD

**Issue by WeigangLu** [mengyangniu/ogbn-papers100m-sage#1]
I have been working with your implementation and I would like to evaluate its performance with more than 3 layers.

Could you kindly provide me with details regarding the hardware setup you employed when working with the model, such as ROM and RAM memory.

**Comment by mengyangniu** [comment]
Apologies for my delayed response. I'm not sure about the exact hardware specifics, since this work is done 3 years ago. The approximate hardware setup as follow:
```
cpu: Intel Xeon Platinum 8163, 2.50GHz, 82 cores (41 cores/thread, 2threads)
gpu: 8 * Nvidia Tesla V100 with 16G ram
mem: 330G
disk: 2T SSD
```
